apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script-configmap
data:
  01-init.sh: |-
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
      CREATE DATABASE ${DB_DATABASE} ENCODING 'UTF-8' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE 'template0';
      CREATE DATABASE ${DB_DATABASE_ANALYTICS} ENCODING 'UTF-8' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE 'template0';
      CREATE USER ${DB_READ_USER} PASSWORD '${DB_READ_PASSWORD}';
      CREATE USER ${DB_WRITE_USER} PASSWORD '${DB_WRITE_PASSWORD}' IN ROLE ${DB_READ_USER};
    EOSQL
  02-role.sh: |-
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${DB_DATABASE}" <<-EOSQL
      CREATE EXTENSION IF NOT EXISTS pgcrypto;
      CREATE EXTENSION IF NOT EXISTS pg_trgm;
      ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_WRITE_USER} IN SCHEMA public GRANT SELECT ON TABLES TO ${DB_READ_USER};
    EOSQL
